import Head from 'next/head'
import Layout from '../components/layout'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Movie db app</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </Layout>
  )
}
